src/proposals/urls.py
from django.urls import path

from . import views

app_name = 'proposals'
urlpatterns = [
    path('', views.home, name='home'),
    path('proposal/new', views.create_proposal, name='create_proposal'),
    path('login', views.login, name='login'),
    path('register', views.register, name='register'),
    path('<int:proposal_id>/', views.proposal, name='proposal'),
    path('proposal/vote', views.vote, name='vote'),
    path('signout', views.signout, name='signout'),
    path('voted/<int:user_id>', views.proposals_voted_on, name='proposals_voted_on')
]

src/src/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('proposals/', include('proposals.urls'))
]

src/proposals/models.py
from django.db import models
from django.db.models import constraints

# from django.contrib.auth.models import User


class Account(models.Model):
    username = models.CharField(max_length=1000, unique=True)
    password_hash = models.CharField(max_length=1000)
    current_auth_token = models.CharField(max_length=1000, null=True)


class Proposal(models.Model):
    description = models.CharField(max_length=1000)
    vote_start_date = models.DateTimeField('date voting starts')
    vote_end_date = models.DateTimeField('date voting ends')
    proposer = models.ForeignKey(Account, on_delete=models.CASCADE)
    yes_votes = models.IntegerField(default=0)
    no_votes = models.IntegerField(default=0)


class ProposalVote(models.Model):
    voter_id = models.ForeignKey(Account, on_delete=models.DO_NOTHING)
    proposal_id = models.ForeignKey(Proposal, on_delete=models.DO_NOTHING)
    vote = models.BooleanField(default=False)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['voter_id', 'proposal_id'], name='One User One Vote')
        ]

src/proposals/views.py
from os import name
from django.db.backends import utils
from django.shortcuts import render
from django.http import HttpResponse, response, HttpResponseRedirect
from django.template import context, loader
from django.shortcuts import render, redirect
from .models import Proposal, Account, ProposalVote
from django.db import connection
from datetime import date, datetime
from .utils.auth import checkPasswordAgainstHash, generateAuthToken, hashPassword, authenticateUser
from .utils.db import get_or_none
from random import randint
from django.utils import timezone


def routeToErrorPage(context, request, status, message):
    context['status'] = status
    context['status_message'] = message
    return render(request, 'proposals/operationstatus.html', context)


def home(request):
    user = authenticateUser(request)
    proposals_list = Proposal.objects.order_by('vote_start_date')
    context = {
        'proposals_list': proposals_list,
        'user': user
    }
    for proposal in proposals_list:
        print(proposal.vote_start_date)
    return render(request, 'proposals/index.html', context)


def create_proposal(request):
    user = authenticateUser(request)
    if user == None:
        return redirect('/proposals/login')
    if request.method == 'POST':
        context = {
            'user': user,
            'status': 'Success',
            'status_message': 'New proposal has been added!'
        }
        text = request.POST['description']
        startDate = datetime.fromisoformat(request.POST['startDate'])
        endDate = datetime.fromisoformat(request.POST['endDate'])
        if startDate > endDate:
            return routeToErrorPage(context, request, 'Unsuccessful',
                                    'Start date can not be after End date!')
        sql = 'INSERT INTO proposals_proposal (description, vote_start_date, vote_end_date, proposer_id, yes_votes, no_votes) VALUES ("{text}", "{startDate}", "{endDate}", "{proposer}", "0", "0");'.format(
            text=text, startDate=startDate.strftime('%Y-%m-%d %H:%M:%S'), endDate=endDate.strftime('%Y-%m-%d %H:%M:%S'), proposer=user.id)

        with connection.cursor() as cursor:
            cursor.execute(sql)
            return render(request, 'proposals/operationstatus.html', context)
    elif request.method == 'GET':
        return render(request, 'proposals/createproposal.html')


def proposal(request, proposal_id):
    if request.method == 'GET':
        user = authenticateUser(request)
        context = {
            'user': user, }
        proposal = get_or_none(Proposal, pk=proposal_id)
        if proposal == None:
            return routeToErrorPage(context, request, 'Unsuccessful',
                                    'Proposal does not exist!')
        userVote = None
        if user != None:
            userVote = ProposalVote.objects.filter(
                voter_id=user.id).filter(proposal_id=proposal.id).first()

        if userVote == None:
            context['user_has_voted'] = False
            context['user_vote'] = None
        else:
            context['user_has_voted'] = True
            context['user_vote'] = userVote.vote

        votingOpen = proposal.vote_start_date < timezone.now(
        ) and timezone.now() < proposal.vote_end_date

        context['proposal'] = proposal
        context['voting_open'] = votingOpen
        return render(request, 'proposals/proposal.html', context)


def vote(request):
    if request.method == 'POST':
        user = authenticateUser(request)
        if user == None:
            return redirect('/proposals/login')
        context = {
            'user': user
        }
        proposal_id = request.POST['proposal_id']
        if proposal_id == None:
            return routeToErrorPage(context, request, 'Unsuccessful',
                                    'Proposal ID not given!')
        vote = request.POST['vote']
        if vote == None:
            return routeToErrorPage(context, request, 'Unsuccessful',
                                    'Vote not given!')
        proposal = Proposal.objects.get(pk=proposal_id)
        if proposal == None:
            return routeToErrorPage(context, request, 'Unsuccessful',
                                    'Proposal does not exist!')
        if not (proposal.vote_start_date < timezone.now() and timezone.now() < proposal.vote_end_date):
            return routeToErrorPage(context, request, 'Unsuccessful',
                                    'Voting is not open!')
        userVote = ProposalVote.objects.filter(
            voter_id=user.id).filter(proposal_id=proposal.id).first()
        if userVote != None:
            routeToErrorPage(context, request, 'Unsuccessful',
                             'Already voted!')
        newVote = ProposalVote(
            voter_id=user, proposal_id=proposal, vote=vote == 'true')
        newVote.save()

        if vote == 'true':
            proposal.yes_votes = proposal.yes_votes + 1
        else:
            proposal.no_votes = proposal.no_votes + 1
        proposal.save()

        context['status'] = 'Success'
        context['status_message'] = 'Voted!'
        context['proposal'] = proposal
        context['user'] = user
        context['user_has_voted'] = True
        context['user_vote'] = vote == 'true'
        return render(request, 'proposals/proposal.html', context)


def proposals_voted_on(request, user_id):
    if request.method == 'GET':
        user = authenticateUser(request)
        context = {
          'user': user
        }

        userVotes = ProposalVote.objects.select_related('proposal_id').filter(voter_id=user_id).all()

        context['user_votes'] = userVotes
        return render(request, 'proposals/voted.html', context)
        

def login(request):
    if request.method == 'POST':
        context = {
            'status': 'Success',
            'status_message': 'New account has been created!'
        }
        username = request.POST['username']
        password = request.POST['password']

        account = Account.objects.filter(username=username).first()
        print(account)
        if account == None or not checkPasswordAgainstHash(password, account.password_hash):
            return routeToErrorPage(context, request, 'Unsuccessful',
                                    'Login unsuccesful! User does not exist or incorrect password!')
        account.current_auth_token = generateAuthToken(
            username=username, randomInteger=randint(a=0, b=1000))
        account.save()
        response = HttpResponseRedirect('/proposals')
        response.set_cookie('auth_token', account.current_auth_token)
        response.set_cookie('username', account.username)
        return response
    elif request.method == 'GET':
        user = authenticateUser(request)
        if user == None:
            return render(request, 'proposals/login.html', {'user': None})

        return redirect('/proposals')


def signout(request):
    user = authenticateUser(request)
    if user == None:
        return redirect('/proposals/login')
    user.current_auth_token = None
    user.save()
    response = HttpResponseRedirect('/proposals')
    response.delete_cookie('auth_token')
    response.delete_cookie('username')
    return response


def register(request):
    if request.method == 'POST':
        user = authenticateUser(request)

        context = {
            'status': 'Success',
            'status_message': 'New account has been created!',
            'user': user
        }
        try:
            username = request.POST['username']
            password = request.POST['password']
            passwordHash = hashPassword(password)

            newAccount = Account(username=username, password_hash=passwordHash)
            newAccount.save()
            request.message = 'New account created!'
        except:
            context['status'] = 'Unsuccessful'
            context['status_message'] = 'Register unsuccessful!'
        return render(request, 'proposals/operationstatus.html', context)
    elif request.method == 'GET':
        user = authenticateUser(request)
        if user == None:
            return render(request, 'proposals/register.html', {'user': None})

        return redirect('/proposals')

src/proposals/templates/proposals/createproposal.html
{% extends 'base.html' %}
{% block title %}
<title>Create proposal</title>
{% endblock title %}

{% block content %}
<h1>Create new proposal</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<a href="javascript:history.back()">Go Back</a>
<form action="{% url 'proposals:create_proposal' %}" method="post">
  {% csrf_token %}
  <input type="text" name="description" id="description">
  <label for="description">Description</label><br>
  <input type="datetime-local" name="startDate" id="startDate">
  <label for="startDate">Start Date</label><br>
  <input type="datetime-local" name="endDate" id="endDate">
  <label for="endDate">End Date</label><br>
  <input type="submit" value="Propose">
</form>
{% endblock content %}

src/proposals/templates/proposals/index.html
{% extends 'base.html' %}
{% block title %}
<title>Proposals</title>
{% endblock title %}

{% block content %}
<h1>Select proposals to vote on</h1>
{% if proposals_list %}
<ul>
  {% for proposal in proposals_list %}
  <li>
    <a href=" /proposals/{{ proposal.id }}/">{{ proposal.description }}</a>
  <span>Voting starts: {{ proposal.vote_start_date }}</span>
  <span>Voting ends: {{ proposal.vote_end_date }}</span>
  </li>
  {% endfor %}
  </ul>
  {% else %}
  <p>There are no proposals</p>
  {% endif %}
  {% endblock content %}

src/proposals/templates/proposals/login.html
{% extends 'base.html' %}
{% block title %}
<title>Login</title>
{% endblock title %}

{% block content %}
<h1>Login</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<form action="{% url 'proposals:login' %}" method="post">
  {% csrf_token %}
  <input type="text" name="username" id="username">
  <label for="username">Username</label><br>
  <input type="password" name="password" id="password">
  <label for="password">Password</label><br>
  <input type="submit" value="login">
</form>
{% endblock content %}

src/proposals/templates/proposals/operationstatus.html
{% extends 'base.html' %}
{% block title %}
    <title>{{ status }}</title>
{% endblock title %}

{% block content %}
   
  <h1>{{ status_message }}</h1>

  <a href="javascript:history.back()">Go Back</a>
  
{% endblock content %}

src/proposals/templates/proposals/proposal.html
{% extends 'base.html' %}
{% block title %}
<title>Proposal {{ proposal.id }}</title>
{% endblock title %}

{% block content %}
<h2>Proposal:</h2>
<div>{{ proposal.description }}</div>
<h2>Voting starts:</h2>
<div>{{ proposal.vote_start_date }}</div>
<h2>Voting ends:</h2>
<div>{{ proposal.vote_end_date }}</div>

<h2>Yes Votes:</h2>
<div>{{ proposal.yes_votes }}</div>
<h2>No Votes:</h2>
<div>{{ proposal.no_votes }}</div>

{% if user %}
{% if user_has_voted %}

<div>You voted: </div>
{% if user_vote %}
<div>Yes</div>
{% else %}
<div>No</div>
{% endif %}
{% else %}

{% if voting_open %}

<form action="{% url 'proposals:vote' %}" method="POST">
  {% csrf_token %}
  <input type="number" name='proposal_id' hidden='true' value={{proposal.id}}>
  <input type="text" name='vote' hidden='true' value='true'>
  <input type="submit" value="Vote Yes">
</form>
<form action="{% url 'proposals:vote' %}" method="POST">
  {% csrf_token %}
  <input type="number" name='proposal_id' hidden='true' value={{proposal.id}}>
  <input type="text" name='vote' hidden='true' value='false'>
  <input type="submit" value="Vote No">
</form>
{% else %}
<div>Voting is not open</div>
{% endif %}
{% endif %}
{% endif %}

{% endblock content %}

src/proposals/templates/proposals/register.html
{% extends 'base.html' %}
{% block title %}
<title>Login</title>
{% endblock title %}

{% block content %}
<h1>Register</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<form action="{% url 'proposals:register' %}" method="post">
  {% csrf_token %}
  <input type="text" name="username" id="username">
  <label for="username">Username</label><br>
  <input type="password" name="password" id="password">
  <label for="password">Password</label><br>
  <input type="submit" value="register">
</form>
{% endblock content %}

src/proposals/templates/proposals/voted.html
{% extends 'base.html' %}
{% block title %}
<title>User votes</title>
{% endblock title %}

{% block content %}
<h1>Users {{ user.username }} votes to proposals</h1>
{% if user_votes %}
<ul>
  {% for vote in user_votes %}
  <li>
    <a href=" /proposals/{{ vote.proposal_id.id }}/">{{ vote.proposal_id.description }}</a>
    {% if vote.vote %}
    <span>Voted: Yes</span>
    {% else %}
    <span>Voted: No</span>
    {% endif %}
  </li>
  {% endfor %}
</ul>
{% else %}
<p>There are no proposals</p>
{% endif %}
{% endblock content %}